spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  datasource:
    schema: classpath*:db/h2/initDB.sql
    data: classpath*:db/h2/populateDB.sql
    name: swagger
