spring:
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: create
    generate-ddl: false
    show-sql: true

  datasource:
    username: root
    password: root
    url: jdbc:postgresql://localhost:5432/SwaggerDocumentation
    driver-class-name: org.postgresql.Driver
